add_newline = false
command_timeout = 2000

[battery]
disabled = true

[character]
success_symbol = "[ꫝ](bold green)"
error_symbol   = "[ꫝ](bold red)"

[directory]
truncation_length = 100
style = "bold blue"

[git_status]
style = "bold cyan"

[line_break]
disabled = true

[python]
python_binary = "python3"

[status]
disabled = false

[package]
disabled = true
