vscode_extensions:
  - bmalehorn.vscode-fish                     # support for fish
  - bradlc.vscode-tailwindcss                 # support for tailwind
  - britesnow.vscode-toggle-quotes            # cycle between single and double quotes
  - charliermarsh.ruff                        # support for ruff
  - dbaeumer.vscode-eslint                    # support for eslint
  - donjayamanne.githistory                   # git log
  - dracula-theme.theme-dracula               # dracula theme
  - esbenp.prettier-vscode                    # prettier code formatter
  - formulahendry.auto-rename-tag             # auto rename html elements
  - ionutvmi.path-autocomplete                # path completion
  - miguelsolorio.fluent-icons                # product icon theme
  - ms-azuretools.vscode-docker               # support for docker
  - ms-python.python                          # support for python
  - rohit-gohri.format-code-action            # format document action for codeActionsOnSave
  - samuelcolvin.jinjahtml                    # jinja syntax highlighting
  - tamasfe.even-better-toml                  # support for toml
