vscode_extensions:
  - bmalehorn.vscode-fish                     # support for fish
  - bradlc.vscode-tailwindcss                 # support for tailwind
  - charliermarsh.ruff                        # support for ruff
  - dbaeumer.vscode-eslint                    # support for eslint
  - dracula-theme.theme-dracula               # dracula theme
  - esbenp.prettier-vscode                    # prettier code formatter
  - ionutvmi.path-autocomplete                # path completion
  - miguelsolorio.fluent-icons                # product icon theme
  - ms-azuretools.vscode-docker               # support for docker
  - ms-python.debugpy                         # support for python debugging
  - ms-python.python                          # support for python
  - ms-python.vscode-pylance                  # language server for python
  - samuelcolvin.jinjahtml                    # jinja syntax highlighting
  - tamasfe.even-better-toml                  # support for toml
